[package]
name = "imgui-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
detour = "0.8.1"
anyhow = "1.0.58"

[dependencies.windows]
version = "0.38.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
]
